---
# tasks file for ansible-role-arc-client
#
#
  - name: print fgci_install
    debug: var=fgci_install verbosity=1

  - name: Remove ARC5 client packages
    yum: name={{arc5_client_packages}} state=absent

  - name: Remove fgi-lsc-files package
    yum: name=fgi-lsc-files state=absent

  - name: Download lsc file from voms.fgi.csc.fi
    shell: arcctl deploy voms-lsc fgi.csc.fi --voms vomss://voms.fgi.csc.fi:8443/voms/fgi.csc.fi
    args:
      executable: /bin/bash

  - name: Download lsc file from voms2.cern.ch
    shell: arcctl deploy voms-lsc ops --voms vomss://voms2.cern.ch:8443/voms/ops
    args:
      executable: /bin/bash

  - name: Install FGCI repo 
    yum: pkg=http://idris.fgi.csc.fi/fgci7/x86_64/fgci/rpms/fgci-release7-1-1.el7.noarch.rpm
    when: ansible_distribution_major_version == "7"

  - name: install packages for arc-client
    yum: pkg={{ arc6_client_packages }} state=installed

  - name: template in fetch-crl.d config
    template: src=fetch-crl.conf dest=/etc/fetch-crl.d/proxy.conf mode=0644 owner=root group=root backup=no

  - name: start fetch-crl-cron
    service: name=fetch-crl-cron state=started enabled=yes
    when: ansible_connection != 'chroot'

  - name: enable fetch-crl-cron in chroot
    command: systemctl enable fetch-crl-cron
    when: ansible_connection == 'chroot'

  - name: add EGI Trustanchors repository
    get_url: url="http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo" dest=/etc/yum.repos.d/egi-trustanchors.repo mode=0644 owner=root
    when: repo_egi_trustanchors|bool

  - name: install repo_egi_packages
    yum: name={{ repo_egi_packages }} state=present
    when: repo_egi_trustanchors|bool

  - name: check if there's a nordugrid-updates.repo
    stat: path=/etc/yum.repos.d/nordugrid-updates.repo
    register: arc_frontend_excludeCAs

  - name: exclude IGTF CAs from Nordugrid repo
    ini_file: dest=/etc/yum.repos.d/nordugrid-updates.repo
        section=nordugrid-updates
        option=exclude
        value=ca_*
        no_extra_spaces=True
        backup=yes
    when: arc_frontend_excludeCAs.stat.exists

  - name: Template ARC client.conf
    template: src=client.conf.j2 dest=/etc/arc/client.conf owner=root mode=0644
    when: arc_client_conf|bool

