---
# tasks file for ansible-role-arc-client
#i
#
  - name: print fgci_install
    debug: var=fgci_install verbosity=1

  - name: Remove ARC5 client packages
    yum: name={{arc5_client_packages}} state=absent

  - name: Remove ARC5 key
    rpm_key:
      state: absent
      key: 240a5db2

  - name: install nordugrid repo
    yum: pkg=https://download.nordugrid.org/packages/nordugrid-release/releases/6/centos/el7/x86_64/nordugrid-release-6-1.el7.noarch.rpm

  - name: install nordugrid rpm key
    rpm_key: key=https://download.nordugrid.org/RPM-GPG-KEY-nordugrid-6 state=present

  - name: check if there's a nordugrid.repo.rpmnew
    stat: path=/etc/yum.repos.d/nordugrid.repo.rpmnew
    register: arc_frontend_rpmnew_stat

  - name: Replace old nordugrid.repo
    command: mv /etc/yum.repos.d/nordugrid.repo.rpmnew /etc/yum.repos.d/nordugrid.repo
    when: arc_frontend_rpmnew_stat.stat.exists

  - name: install packages for arc-client
    yum: pkg={{ arc6_client_packages }} state=installed

  - name: template in fetch-crl.d config
    template: src=fetch-crl.conf dest=/etc/fetch-crl.d/proxy.conf mode=0644 owner=root group=root backup=no

  - name: start fetch-crl-cron
    service: name=fetch-crl-cron state=started enabled=yes
    when: ansible_connection != 'chroot'

  - name: enable fetch-crl-cron in chroot
    command: systemctl enable fetch-crl-cron
    when: ansible_connection == 'chroot'

  - name: add EGI Trustanchors repository
    get_url: url="http://repository.egi.eu/sw/production/cas/1/current/repo-files/EGI-trustanchors.repo" dest=/etc/yum.repos.d/egi-trustanchors.repo mode=0644 owner=root
    when: repo_egi_trustanchors|bool

  - name: install repo_egi_packages
    yum: name={{ repo_egi_packages }} state=present
    when: repo_egi_trustanchors|bool

  - name: check if there's a nordugrid-updates.repo
    stat: path=/etc/yum.repos.d/nordugrid-updates.repo
    register: arc_frontend_excludeCAs

  - name: exclude IGTF CAs from Nordugrid repo
    ini_file: dest=/etc/yum.repos.d/nordugrid-updates.repo
        section=nordugrid-updates
        option=exclude
        value=ca_*
        no_extra_spaces=True
        backup=yes
    when: arc_frontend_excludeCAs.stat.exists

  - name: Template ARC client.conf
    template: src=client.conf.j2 dest=/etc/arc/client.conf owner=root mode=0644
    when: arc_client_conf|bool

